export const AUTH_ROUTE = '/auth'
export const REG_ROUTE = '/register'
export const FEED_ROUTE = '/feed'
export const HOME_ROUTE = '/'
export const POST_ROUTE = '/post'
export const USER_ROUTE = '/user'
export const SUB_ROUTE = '/user/:id/sub'
export const SUBS_ROUTE = '/user/:id/subs'